--California State University, San Bernardino
--Department of Computer Science
--Course: 572
-- Robert Moya 
--
-- Taxi
--Altering Table adding constraints

ALTER TABLE Office
	ADD CONSTRAINTS Office_FK FOREIGN KEY (employeeId)
	REFERENCES Staff(employeeID)
	ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Staff
	ADD CONSTRAINTS Staff_FK FOREIGN KEY (officeId)
	REFERENCES Office(officeId)
	ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Manager
	ADD CONSTRAINTS Manager_FK FOREIGN KEY (employeeId)
	REFERENCES Staff(employeeId)	
	ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Taxi
	ADD CONSTRAINTS Taxi_FK FOREIGN KEY (employeeId)
	REFERENCES Staff(employeeId)
	ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Job
	ADD CONSTRAINTS Job_employeeID_FK FOREIGN KEY (employeeId)
	REFERENCES Staff(employeeId)
	ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Job
	ADD CONSTRAINTS Job_contractNumber_FK FOREIGN KEY (contractNumber)
	REFERENCES Contract(contractNumber)
	ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Job
	ADD CONSTRAINTS Job_clientID_FK FOREIGN KEY (clientId)
	REFERENCES Private(clientId)	
	ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Job
	ADD CONSTRAINTS Job_Taxi_FK FOREIGN KEY (taxiId)
	REFERENCES Taxi(employeeId)
	ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Contract
	ADD CONSTRAINTS Contract_Client_FK FOREIGN KEY (clientId)
	REFERENCES Business(clientID)
	ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Contract
	ADD CONSTRAINTS Contract_OfficeId_FK FOREIGN KEY (officeId)
	REFERENCES Office(officeId)
	ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Business
	ADD CONSTRAINTS Businees_OfficeId_FK FOREIGN KEY (officeId)
	REFERENCES Office(officeId)
	ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Business
	ADD CONSTRAINTS Business_JobId_FK FOREIGN KEY (jobId)
	REFERENCES Job(jobId)	
	ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Private
	ADD CONSTRAINTS Private_officeId_FK FOREIGN KEY (officeId)
	REFERENCES Office(officeId)
	ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE TaxiDriver
	ADD CONSTRAINTS TaxiDriver_StaffId_FK FOREIGN KEY (employeeId)
	REFERENCES Staff(employeeId)	
	ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE TaxiDriver
	ADD CONSTRAINTS TaxiDriver_TaxiId_FK FOREIGN KEY (taxiId)
	REFERENCES Taxi(employeeId)	
	ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
